platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'



def common_Pods
    pod 'MJRefresh'
    pod 'ReactiveCocoa’,'~> 2.4.7’
    pod 'Masonry’,'~> 1.1.0’
    pod 'WebViewJavascriptBridge’,'~> 6.0.2’
    pod 'FLAnimatedImage', '~> 1.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'YYCache'
    pod 'FLEX’
    pod 'ZHXIndexView', '~> 0.0.1'
    pod 'BlocksKit’
end

target 'KnowledgeSummaryOfObjectC' do
      common_Pods
end

target 'TargetOne' do
      common_Pods
end
