platform :ios, '14.0'


source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:zhangxistudy11/ZHXFindRepos.git'

def common_Pods
    pod 'MJRefresh'
    pod 'ReactiveObjC’
    pod 'Masonry’
    pod 'WebViewJavascriptBridge’
    pod 'FLAnimatedImage'
    pod 'MBProgressHUD'
    pod 'YYCache'
    pod 'BlocksKit’
    pod 'ZHXIndexView'
    pod 'ZHXFindPro', '= 0.3.7'

end

target 'KnowledgeSummaryOfObjectC' do
      common_Pods
end

target 'TargetOne' do
      common_Pods
end
